//
// Created by 郑虎 on 2016-02-22.
//

#ifndef GAMEOFLIF_TWODIMENSIONALGEOMETRICBUFFER_HPP
#define GAMEOFLIF_TWODIMENSIONALGEOMETRICBUFFER_HPP

class TwoDimensionalGeometricBuffer {

};

#endif //GAMEOFLIF_TWODIMENSIONALGEOMETRICBUFFER_HPP
